### PR TITLE
My logo proposal

### PR DESCRIPTION
**Pull request by mmaayylliiss**

### CODE REVIEW

**Comment by vvatikiotis** [comment]
What's this M on the left hand side?

**Comment by mmaayylliiss** [comment]
Do you speak of my logo, not Euruko logo?
'M' is simply the first letter of my first name 'Maylis'.

**Comment by vvatikiotis** [comment]
Lol, i got confused, your logo looks a bit like the ruby

**Comment by giedriusr** [comment]
:DDD that's true

**Comment by mmaayylliiss** [comment]
Hihi ^^

**Comment by nikosd** [comment]
It reminds a little bit the acropolis rally :D

**Comment by nikosd** [comment]
Logo is decided and you'll be able to see it soon on the site :smile:

**Pull request closed without merging**
