### PR TITLE
skroutz proposal (5)

### PR DESCRIPTION
**Pull request by chief**

### CODE REVIEW

**Comment by fotos** [comment]
:+1: :+1:

I dig the Antikythera mechanism and the overall logo feeling.

**Comment by nikosd** [comment]
:thumbsup:

**Comment by vrinek** [comment]
:+1:

**Comment by teoulas** [comment]
:+1:

**Comment by pagojo** [comment]
not bad :-)

**Comment by vvatikiotis** [comment]
this one is great as an idea. Whould the mechanism be a bit more visible?

**Comment by mikezaby** [comment]
:+1: for more visible mechanism, also i would like a bigger ruby :tongue:

**Comment by alup** [comment]
I agree with @mikezaby 
I believe, this could be the best with the enhancements.

**Comment by giedriusr** [comment]
yes, I agree :) this one is really nice

**Comment by damphyr** [comment]
:+1: and make the mechanism more visible. Also do a negative to print on black t-shirts :)

**Comment by teoulas** [comment]
:+1: for the planets=rubies idea

**Comment by vvatikiotis** [comment]
this one seems to have the most positive reviews

**Comment by fotos** [comment]
Yes indeed this design has the most votes, as of right now.

@chief can we ask Bill to iterate a bit on this design and refine it?
1. more visible mechanism / background circles
2. rubies as planets (?)
3. more distinct ruby in 0 in 2012 or even without it?
4. a white version that would print well on dark colored / black tshirts?

**Comment by teoulas** [comment]
@fotos now that you mentioned t-shirts, in one of our meetings we discussed that it would look nice on these: https://github.com/chief/general/blob/414c2754853b634ecd49725d92bb7ee1f8f7510e/logo/skroutz-8/logo_tanos%20%281%29.jpg (with a ruby printed on the side)

**Comment by damphyr** [comment]
Oh, I like those t-shirts (the ruby on the side is really cool) but I like this logo more. Combine?

**Comment by teoulas** [comment]
Yup that was the idea, have the ruby on the side + this logo in front

**Comment by giedriusr** [comment]
Ruby on the side looks nice, although the main logo should be different

**Comment by nikosd** [comment]
Logo is decided and you'll be able to see it soon on the site :smile:

**Pull request closed without merging**
