### PR TITLE
skroutz logo proposal (8)

### PR DESCRIPTION
**Pull request by chief**

### CODE REVIEW

**Comment by fotos** [comment]
:+1:

I dig this, plain and simple. Even tho, personally, I still prefer the [Anti-Kythera one](https://github.com/euruko2013/general/pull/13) which is a bit more arty.

**Comment by mikezaby** [comment]
:+1:

**Comment by vrinek** [comment]
:+1: plain 'n' simple

**Comment by alup** [comment]
:+1:

**Comment by pagojo** [comment]
Not too bad :-)

**Comment by vvatikiotis** [comment]
:+1: :+1:

**Comment by nikosd** [comment]
Logo is decided and you'll be able to see it soon on the site :smile:

**Pull request closed without merging**
