### PR TITLE
skroutz proposal (10)

### PR DESCRIPTION
**Pull request by chief**

### CODE REVIEW

**Comment by fotos** [comment]
Jesus! Wel 'll got to hell (coding VB) if we print this on tshirts!

**Comment by pagojo** [comment]
Really NOT having this!

**Comment by pagojo** [comment]
:-1:

**Comment by vvatikiotis** [comment]
ruby sect? :D

**Comment by damphyr** [comment]
yikes! :-1:

**Comment by nikosd** [comment]
Logo is decided and you'll be able to see it soon on the site :smile:

**Pull request closed without merging**
